<Project>
  <PropertyGroup>
    <RepositoryRoot>$(MSBuildThisFileDirectory)</RepositoryRoot>
    <Cities2ManagedPath Condition="'$(Cities2ManagedPath)' == '' and '$(CITIES2_MANAGED_PATH)' != ''">$(CITIES2_MANAGED_PATH)</Cities2ManagedPath>
    <InterchangeBuilderAssembly Condition="'$(InterchangeBuilderAssembly)' == '' and '$(INTERCHANGEBUILDER_ASSEMBLY)' != ''">$(INTERCHANGEBUILDER_ASSEMBLY)</InterchangeBuilderAssembly>
    <InterchangeBuilderAssembly Condition="'$(InterchangeBuilderAssembly)' == ''">$(MSBuildThisFileDirectory)vendor\InterchangeBuilder-Base\InterchangeBuilder.dll</InterchangeBuilderAssembly>
  </PropertyGroup>
</Project>
