<Project>
  <PropertyGroup>
    <RepositoryRoot>$(MSBuildThisFileDirectory)</RepositoryRoot>
    <Cities2ManagedPath Condition="'$(Cities2ManagedPath)' == '' and '$(CITIES2_MANAGED_PATH)' != ''">$(CITIES2_MANAGED_PATH)</Cities2ManagedPath>
    <OriginalInterchangeBuilderAssembly Condition="'$(OriginalInterchangeBuilderAssembly)' == '' and '$(INTERCHANGEBUILDER_ORIGINAL_ASSEMBLY)' != ''">$(INTERCHANGEBUILDER_ORIGINAL_ASSEMBLY)</OriginalInterchangeBuilderAssembly>
    <OriginalInterchangeBuilderAssembly Condition="'$(OriginalInterchangeBuilderAssembly)' == ''">$(MSBuildThisFileDirectory)vendor\InterchangeBuilder-1.4.2\InterchangeBuilder.dll</OriginalInterchangeBuilderAssembly>
  </PropertyGroup>
</Project>
