<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>InterchangeBuilder.LaneConnections</AssemblyName>
    <RootNamespace>InterchangeBuilder.LaneConnections</RootNamespace>
    <Version>2.3.0</Version>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\InterchangeBuilder.LaneConnections.Core\InterchangeBuilder.LaneConnections.Core.csproj" />
    <PackageReference Include="Lib.Harmony" Version="2.2.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="InterchangeBuilder">
      <HintPath>$(InterchangeBuilderAssembly)</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Game">
      <HintPath>$(Cities2ManagedPath)\Game.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Colossal.Logging">
      <HintPath>$(Cities2ManagedPath)\Colossal.Logging.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Colossal.Core">
      <HintPath>$(Cities2ManagedPath)\Colossal.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Colossal.UI.Binding">
      <HintPath>$(Cities2ManagedPath)\Colossal.UI.Binding.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Entities">
      <HintPath>$(Cities2ManagedPath)\Unity.Entities.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>$(Cities2ManagedPath)\Unity.Mathematics.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Colossal.Mathematics">
      <HintPath>$(Cities2ManagedPath)\Colossal.Mathematics.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
